id: IF518E40E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T14:11:04+00:00'
last_modified: '2022-06-08T01:45:42.696761+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17649
  title: ཞལ་འདོན་ཆོས་སྤྱོད་ཉུང་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E8BB:
      image_group_id: I2PD19545
      title: ''
      total_pages: 122
      order: 1
      base_file: E8BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
