id: P004534
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:30:33.003179
source_metadata:
  id: bdr:W2PD17649
  title: ཞལ་འདོན་ཆོས་སྤྱོད་ཉུང་བསྡུས།
  author: ''
  volumes:
    4b8d30289d884ac0b0be28c673098d01:
      image_group_id: I2PD19545
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
